#!/bin/bash

source /etc/jelastic/environment

cd ${OPENSHIFT_RAILO4j_DIR}/versions/${Version}/

if [ -x ${OPENSHIFT_RAILO4j_DIR}/versions/${Version}/bin/variablesparser.sh ]; then
    . ${OPENSHIFT_RAILO4j_DIR}/versions/${Version}/bin/variablesparser.sh
fi

jetty_pid=`ps aux|grep java|grep jetty|grep -v grep|awk '{print $2}'`;

[ -n "$jetty_pid" ] && echo "Server already started" && exit 0;

CMD="java ${JAVA_OPTS} -jar start.jar -Djetty.host=$OPENSHIFT_RAILO4j_APP_HOST -Djetty.port=$OPENSHIFT_RAILO4j_APP_PORT"

nohup $CMD >> $OPENSHIFT_RAILO4j_LOG_DIR/server.log 2>&1 &

echo $! > jetty.pid && echo "Railo server started successfully"
